### ISSUE TITLE
flask_cors is installed but it says like this

### ISSUE THREAD

**Issue by GodTierCutie** [FujiwaraChoki/nook#2]
Traceback (most recent call last):
  File "E:\Rain\Github\FujiwaraChoki\nook\server\main.py", line 5, in <module>
    from flask_cors import CORS
ModuleNotFoundError: No module named 'flask_cors'

**Comment by FujiwaraChoki** [comment]
You probably used the wrong interpreter.

Try this:

```bash
py -m pip install -r requirements.txt
```

Then run the python backend with `py` instead of `python`.
